hello:
  build: .
  command: node_modules/.bin/nodemon app.js
  environment:
    NODE_ENV: development
  ports:
    - '3000:3000'
  volumes:
    - .:/home/app/hello
    - /home/app/hello/node_modules
